import './globals.scss'
import style from './layout.module.scss'
import { Nunito_Sans } from 'next/font/google'
import MenuV2 from "@/app/components/Menu/MenuV2";

const nunitoSans = Nunito_Sans({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={nunitoSans.className}>
        <div className={style.Wrapper}>
          <div className={style.Content}>
            {children}
          </div>
          <div className={style.Menu}>
            <MenuV2 />
          </div>
        </div>
      </body>
    </html>
  )
}
