export const activityTypeFilterValues = [
    { label: "Academic News", value: "Academic News" },
    { label: "Announcement", value: "Announcement" },
    { label: "Archivum News", value: "Archivum News" },
    { label: "Book Launch", value: "Book Launch" },
    { label: "Collections News", value: "Collections News" },
    { label: "Community", value: "Community" },
    { label: "Conference", value: "Conference" },
    { label: "Education Program", value: "Education Program" },
    { label: "Film Screening", value: "Film Screening" },
    { label: "Internship", value: "Internship" },
    { label: "Job", value: "Job" },
    { label: "Join Us", value: "Join Us" },
    { label: "Lecture", value: "Lecture" },
    { label: "Library", value: "Library" },
    { label: "Music", value: "Music" },
    { label: "Partner Projects", value: "Partner Projects" },
    { label: "Performance", value: "Performance" },
    { label: "Program Series", value: "Program Series" },
    { label: "Public Program News", value: "Public Program News" },
    { label: "Publication", value: "Publication" },
    { label: "Research", value: "Research" },
    { label: "Round Table", value: "Round Table" },
    { label: "Scholarship", value: "Scholarship" },
    { label: "Talk", value: "Talk" },
    { label: "Theatre", value: "Theatre" },
    { label: "University Course", value: "University Course" },
    { label: "Workshop", value: "Workshop" },
]